apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    component: gstack
type: Opaque
stringData:
  username: gstack
  password: gstack_password
  url: postgres://gstack:gstack_password@postgres-service:5432/gstack
