apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmirror.fullname" . }}
  labels:
    {{- include "gmirror.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.healthPort }}
    targetPort: health
    protocol: TCP
    name: health
  selector:
    {{- include "gmirror.selectorLabels" . | nindent 4 }}
