import type { CareCircleGraph } from '@dyad/shared';

export const careCircleFixture: CareCircleGraph = {
  id: 'carecircle-demo',
  name: 'Linda family circle',
  people: [
    {
      id: 'linda',
      name: 'Linda',
      role: 'parent',
      relationshipLabel: 'Aging mother',
      communicationPreference: 'Morning calls with concrete choices',
      responsibilities: ['Stay independent', 'Share changes when comfortable'],
      notes: ['Gets defensive when help sounds like control'],
    },
    {
      id: 'maya',
      name: 'Maya',
      role: 'daughter',
      relationshipLabel: 'Daughter / primary coordinator',
      communicationPreference: 'Coordinates through family messages',
      responsibilities: ['Gentle check-ins', 'Sibling coordination'],
    },
    {
      id: 'sarah',
      name: 'Sarah',
      role: 'sibling',
      relationshipLabel: 'Sibling / pharmacy owner',
      responsibilities: ['Call pharmacy', 'Track medication questions'],
    },
    {
      id: 'arjun',
      name: 'Arjun',
      role: 'sibling',
      relationshipLabel: 'Sibling / appointments owner',
      responsibilities: ['Confirm appointments', 'Maintain calendar tasks'],
    },
    {
      id: 'dr-chen',
      name: 'Dr. Chen',
      role: 'doctor',
      relationshipLabel: 'Doctor',
      responsibilities: ['Review medical questions'],
    },
    {
      id: 'pharmacy',
      name: 'Local pharmacy',
      role: 'pharmacist',
      relationshipLabel: 'Pharmacy',
      responsibilities: ['Medication guidance'],
    },
  ],
  relationships: [
    {
      id: 'rel-maya-linda',
      fromPersonId: 'maya',
      toPersonId: 'linda',
      type: 'family',
      context: 'Maya is Linda’s daughter and primary coordinator.',
      trustNotes: ['Linda responds better when Maya frames support around independence.'],
    },
    {
      id: 'rel-sarah-linda',
      fromPersonId: 'sarah',
      toPersonId: 'linda',
      type: 'family',
      context: 'Sarah is a sibling helping with pharmacy follow-up.',
    },
    {
      id: 'rel-arjun-linda',
      fromPersonId: 'arjun',
      toPersonId: 'linda',
      type: 'family',
      context: 'Arjun is a sibling helping with appointments and calendar tasks.',
    },
    {
      id: 'rel-dr-chen-linda',
      fromPersonId: 'dr-chen',
      toPersonId: 'linda',
      type: 'clinical',
      context: 'Dr. Chen is Linda’s doctor.',
    },
    {
      id: 'rel-pharmacy-linda',
      fromPersonId: 'pharmacy',
      toPersonId: 'linda',
      type: 'pharmacy',
      context: 'The local pharmacy can advise on medication timing, dosage, and side effects.',
    },
  ],
  observations: [
    {
      id: 'obs-med-change-1',
      personId: 'linda',
      text: 'Blood pressure medication changed five days ago.',
      timestamp: '2026-05-11T09:00:00.000Z',
      source: 'medication',
      tags: ['medication', 'blood-pressure'],
      sensitivity: 'high',
    },
    {
      id: 'obs-skipped-lunch-1',
      personId: 'linda',
      text: 'Linda skipped lunch on Tuesday.',
      timestamp: '2026-05-12T20:15:00.000Z',
      source: 'family_note',
      tags: ['meal', 'routine-change'],
      sensitivity: 'medium',
    },
    {
      id: 'obs-skipped-lunch-2',
      personId: 'linda',
      text: 'Linda skipped lunch again on Friday.',
      timestamp: '2026-05-15T20:05:00.000Z',
      source: 'family_note',
      tags: ['meal', 'routine-change'],
      sensitivity: 'medium',
    },
    {
      id: 'obs-appointment-repeat-1',
      personId: 'linda',
      text: 'Linda asked about the same appointment for the first time.',
      timestamp: '2026-05-13T16:10:00.000Z',
      source: 'appointment',
      tags: ['appointment', 'repetition'],
      sensitivity: 'medium',
    },
    {
      id: 'obs-appointment-repeat-2',
      personId: 'linda',
      text: 'Linda asked about the same appointment for the second time.',
      timestamp: '2026-05-13T18:30:00.000Z',
      source: 'message',
      tags: ['appointment', 'repetition'],
      sensitivity: 'medium',
    },
    {
      id: 'obs-appointment-repeat-3',
      personId: 'linda',
      text: 'Linda asked about the same appointment for the third time.',
      timestamp: '2026-05-14T17:05:00.000Z',
      source: 'message',
      tags: ['appointment', 'repetition'],
      sensitivity: 'medium',
    },
    {
      id: 'obs-appointment-repeat-4',
      personId: 'linda',
      text: 'Linda asked about the same appointment for the fourth time.',
      timestamp: '2026-05-15T18:40:00.000Z',
      source: 'message',
      tags: ['appointment', 'repetition'],
      sensitivity: 'medium',
    },
    {
      id: 'obs-dizziness-1',
      personId: 'linda',
      text: 'Linda mentioned dizziness on Thursday morning.',
      timestamp: '2026-05-14T17:20:00.000Z',
      source: 'family_note',
      tags: ['dizziness', 'medication-review'],
      sensitivity: 'high',
    },
    {
      id: 'obs-dizziness-2',
      personId: 'linda',
      text: 'Linda mentioned dizziness again on Friday.',
      timestamp: '2026-05-15T19:10:00.000Z',
      source: 'family_note',
      tags: ['dizziness', 'medication-review'],
      sensitivity: 'high',
    },
    {
      id: 'obs-sarah-pharmacy-1',
      personId: 'sarah',
      text: 'Sarah said she can call the pharmacy.',
      timestamp: '2026-05-15T22:30:00.000Z',
      source: 'task',
      tags: ['pharmacy', 'task-owner'],
      sensitivity: 'low',
    },
    {
      id: 'obs-arjun-calendar-1',
      personId: 'arjun',
      text: 'Arjun handles calendar tasks.',
      timestamp: '2026-05-15T23:00:00.000Z',
      source: 'task',
      tags: ['appointment', 'task-owner'],
      sensitivity: 'low',
    },
    {
      id: 'obs-defensive-control-1',
      personId: 'linda',
      text: 'Linda gets defensive when help sounds like control.',
      timestamp: '2026-05-15T23:30:00.000Z',
      source: 'family_note',
      tags: ['communication', 'trust'],
      sensitivity: 'low',
    },
    {
      id: 'obs-morning-concrete-choices-1',
      personId: 'linda',
      text: 'Linda responds better to morning calls and concrete choices.',
      timestamp: '2026-05-15T23:45:00.000Z',
      source: 'family_note',
      tags: ['communication', 'trust'],
      sensitivity: 'low',
    },
  ],
  events: [
    {
      id: 'event-med-change',
      title: 'Blood pressure medication changed',
      timestamp: '2026-05-11T09:00:00.000Z',
      category: 'medication',
      relatedPersonIds: ['linda', 'dr-chen', 'pharmacy'],
      linkedObservationIds: ['obs-med-change-1'],
    },
    {
      id: 'event-skipped-lunch',
      title: 'Skipped lunch twice',
      timestamp: '2026-05-15T20:05:00.000Z',
      category: 'meal',
      relatedPersonIds: ['linda'],
      linkedObservationIds: ['obs-skipped-lunch-1', 'obs-skipped-lunch-2'],
    },
    {
      id: 'event-repeated-appointment',
      title: 'Asked about the same appointment four times',
      timestamp: '2026-05-15T18:40:00.000Z',
      category: 'appointment',
      relatedPersonIds: ['linda', 'arjun'],
      linkedObservationIds: [
        'obs-appointment-repeat-1',
        'obs-appointment-repeat-2',
        'obs-appointment-repeat-3',
        'obs-appointment-repeat-4',
      ],
    },
    {
      id: 'event-dizziness',
      title: 'Dizziness mentioned twice',
      timestamp: '2026-05-15T19:10:00.000Z',
      category: 'symptom',
      relatedPersonIds: ['linda'],
      linkedObservationIds: ['obs-dizziness-1', 'obs-dizziness-2', 'obs-med-change-1'],
    },
    {
      id: 'event-pharmacy-open',
      title: 'Pharmacy call still open',
      timestamp: '2026-05-15T22:30:00.000Z',
      category: 'task',
      relatedPersonIds: ['sarah', 'linda', 'pharmacy'],
      linkedObservationIds: ['obs-sarah-pharmacy-1', 'obs-dizziness-1', 'obs-dizziness-2'],
    },
  ],
  responsibilities: [
    {
      id: 'resp-maya-checkin',
      ownerPersonId: 'maya',
      subjectPersonId: 'linda',
      title: 'Ask Linda three gentle questions',
      status: 'open',
      priority: 'high',
      due: '2026-05-16T19:00:00.000Z',
      linkedObservationIds: ['obs-dizziness-1', 'obs-dizziness-2', 'obs-morning-concrete-choices-1'],
    },
    {
      id: 'resp-sarah-pharmacy',
      ownerPersonId: 'sarah',
      subjectPersonId: 'linda',
      title: 'Call the pharmacy',
      status: 'open',
      priority: 'high',
      due: '2026-05-16T23:00:00.000Z',
      linkedObservationIds: ['obs-sarah-pharmacy-1', 'obs-med-change-1'],
    },
    {
      id: 'resp-arjun-appointment',
      ownerPersonId: 'arjun',
      subjectPersonId: 'linda',
      title: 'Confirm the appointment',
      status: 'open',
      priority: 'medium',
      due: '2026-05-16T23:00:00.000Z',
      linkedObservationIds: [
        'obs-arjun-calendar-1',
        'obs-appointment-repeat-1',
        'obs-appointment-repeat-2',
        'obs-appointment-repeat-3',
        'obs-appointment-repeat-4',
      ],
    },
  ],
  loops: [
    {
      id: 'loop-pharmacy-call',
      description: 'Pharmacy call not completed',
      status: 'open',
      relatedPersonIds: ['sarah', 'linda', 'pharmacy'],
      evidenceObservationIds: ['obs-sarah-pharmacy-1', 'obs-dizziness-1', 'obs-dizziness-2', 'obs-med-change-1'],
      suggestedNextStep:
        'Sarah calls the pharmacy and asks whether medication timing, dosage, or side effects should be reviewed.',
      openedAt: '2026-05-15T22:30:00.000Z',
    },
    {
      id: 'loop-doctor-questions',
      description: 'Doctor visit questions not prepared',
      status: 'open',
      relatedPersonIds: ['maya', 'linda', 'dr-chen'],
      evidenceObservationIds: ['obs-dizziness-1', 'obs-dizziness-2', 'obs-skipped-lunch-1', 'obs-skipped-lunch-2'],
      suggestedNextStep: 'Maya writes three gentle questions for human review before the doctor or pharmacist follow-up.',
      openedAt: '2026-05-15T23:10:00.000Z',
    },
    {
      id: 'loop-sibling-update',
      description: 'Sibling update overdue',
      status: 'open',
      relatedPersonIds: ['maya', 'sarah', 'arjun'],
      evidenceObservationIds: ['obs-sarah-pharmacy-1', 'obs-arjun-calendar-1', 'obs-appointment-repeat-4'],
      suggestedNextStep: 'Send one sibling update with task owners and no medical assumptions.',
      openedAt: '2026-05-15T23:30:00.000Z',
    },
  ],
};
